services:
#  gateway:
#    image: gateway
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - SPRING_PROFILES_ACTIVE=prod,api-docs,zipkin
#      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
#      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
#      - SPRING_CLOUD_CONSUL_HOST=consul
#      - SPRING_CLOUD_CONSUL_PORT=8500
#      - SPRING_R2DBC_URL=r2dbc:postgresql://gateway-postgresql:5432/gateway
#      - SPRING_LIQUIBASE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway
#    ports:
#      - 8080:8080
#    healthcheck:
#      test:
#        - CMD
#        - curl
#        - -f
#        - http://localhost:8080/management/health
#      interval: 5s
#      timeout: 5s
#      retries: 40
#    depends_on:
#      gateway-postgresql:
#        condition: service_healthy
#  gateway-postgresql:
#    image: postgres:17.4
#    environment:
#      - POSTGRES_USER=gateway
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    healthcheck:
#      test:
#        - CMD-SHELL
#        - pg_isready -U $${POSTGRES_USER}
#      interval: 5s
#      timeout: 5s
#      retries: 10

#  microservice:
#    image: microservice
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - SPRING_PROFILES_ACTIVE=prod,api-docs,zipkin
#      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
#      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
#      - SPRING_CLOUD_CONSUL_HOST=consul
#      - SPRING_CLOUD_CONSUL_PORT=8500
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://microservice-postgresql:5432/microservice
#      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microservice-postgresql:5432/microservice
#    healthcheck:
#      test:
#        - CMD
#        - curl
#        - -f
#        - http://localhost:8081/management/health
#      interval: 5s
#      timeout: 5s
#      retries: 40
#    depends_on:
#      microservice-postgresql:
#        condition: service_healthy
#  microservice-postgresql:
#    image: postgres:17.4
#    environment:
#      - POSTGRES_USER=microservice
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    healthcheck:
#      test:
#        - CMD-SHELL
#        - pg_isready -U $${POSTGRES_USER}
#      interval: 5s
#      timeout: 5s
#      retries: 10

  consul:
    image: docker.io/bitnami/consul:1.21.0
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
  consul-config-loader:
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500

  zipkin:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 127.0.0.1:9411:9411

  caddy:
    image: "abiosoft/caddy:latest"
    volumes:
      - ./caddy/certs:/root/certs # to sync mkcert certificates to Caddy
      - ./caddy/Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "443:2015"
#    depends_on:
#      - gateway
#      - microservice