package com.github.joao_felisberto.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhoneNumberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneNumberAllPropertiesEquals(PhoneNumber expected, PhoneNumber actual) {
        assertPhoneNumberAutoGeneratedPropertiesEquals(expected, actual);
        assertPhoneNumberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneNumberAllUpdatablePropertiesEquals(PhoneNumber expected, PhoneNumber actual) {
        assertPhoneNumberUpdatableFieldsEquals(expected, actual);
        assertPhoneNumberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneNumberAutoGeneratedPropertiesEquals(PhoneNumber expected, PhoneNumber actual) {
        assertThat(actual)
            .as("Verify PhoneNumber auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneNumberUpdatableFieldsEquals(PhoneNumber expected, PhoneNumber actual) {
        assertThat(actual)
            .as("Verify PhoneNumber relevant properties")
            .satisfies(a -> assertThat(a.getCountryCode()).as("check countryCode").isEqualTo(expected.getCountryCode()))
            .satisfies(a -> assertThat(a.getNumber()).as("check number").isEqualTo(expected.getNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhoneNumberUpdatableRelationshipsEquals(PhoneNumber expected, PhoneNumber actual) {
        // empty method
    }
}
